### ISSUE TITLE
SFML.Graphics.Text GetGlobalBounds "External component has thrown an exception."

### ISSUE THREAD

**Issue by Zarickan** [SFML/SFML.Net#123]
Sometimes when I try to get the Global Bounds of a Text object i get a SEHException:
An unhandled exception of type 'System.Runtime.InteropServices.SEHException' occurred in sfmlnet-graphics-2.dll
Additional information: External component has thrown an exception.

This is not a one of exception, i can run my game for some time and get this exception, when I do the  characters drawn on screen turns into white squares, and the exception crashes the game.

**Comment by zsbzsb** [comment]
Let's make a few things clear. [A SEHException is thrown when unmanaged memory throws an unhandled exception or experiences a fault](http://blogs.msdn.com/b/cbrumme/archive/2003/04/15/51332.aspx). Also standard exceptions such as out of memory or an access violation map to the equivalent .Net exceptions. So that means the exception is a non standard exception so either SFML or something else is causing it.

Now SFML and CSFML do not throw any of their own exceptions (yet... wait until 3.0). All errors are handled through return values. So if an unhandled exception is being thrown it is not caused by SFML nor is it a standard exception.... something is throwing an exception outside of SFML (such as the driver as that has never happened before) or a [third party program is causing it](http://stackoverflow.com/a/6910644). I'm leaning towards a driver issue as you said your program runs for a bit before crashing.

However unless you provide a complete and minimal code example that reproduces the problem I'm heavily inclined to think it is something specific to your machine (as I know of no other reports of this problem). In the case you can write a complete and minimal example that reproduces the problem please open a thread on the forums and let's continue the discussion there. We try to keep the tracker for confirmed bugs/features only.

**Comment by Zarickan** [comment]
I just have an sgml Text object, and then Use GetGlobalBounds(); to get the bounds of the text, use that in my update loop to center it in a tooltip.
