### ISSUE TITLE
Issues with copying ConvexShape/ConvexShape's points

### ISSUE THREAD

**Issue by NedoProgrammer** [SFML/SFML.Net#203]
Hello! 
In my project, I tried copying a `ConvexShape`, which resulted in an exception. So, I tried copying the points, which resulted in two different `ConvexShape`s.

# Exception (Copying `ConvexShape`)
```cs
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SFML.Graphics.ConvexShape.GetPointCount()
   at SFML.Graphics.Shape.InternalGetPointCount(IntPtr userData)
   at SFML.Graphics.Shape.sfShape_setOutlineThickness(IntPtr CPointer, Single Thickness)
   at SFML.Graphics.Shape.set_OutlineThickness(Single value)
   at SFML.Graphics.Shape..ctor(Shape copy)
   at SFML.Graphics.ConvexShape..ctor(ConvexShape copy)
   at BrokenConvexShape.Program.Main(String[] args) in C:\Users\nedo\RiderProjects\BrokenConvexShape\Program.cs:line 12
```

# Minimal code example
Copying ConvexShape: https://gist.github.com/NedoProgrammer/d8cbe2b4bcad314dd8c79a40e2c4e032
Copying ConvexShapes myself: https://gist.github.com/NedoProgrammer/2be38d4f681cf176ad80c8e534c66baa

# Copying points manually
...results in this:
![изображение](https://user-images.githubusercontent.com/65343244/136669345-724d3341-40e1-408f-9e5e-b955cce28bc1.png)
where the red filled shape is the original shape, and the white outline is the copied shape.

**Comment by DangerRoss** [comment]
@eXpl0it3r or @DemoXinMC You might want to mark this as a bug for SFML.Net.

Following the call stack of the copy constructor of ConvexShape, it looks like it will attempt to read the point count before the constructor actually initialises it.

The Shape base constructor is called first which will set OutlineThickness. In SFML this will cause a shape update that retrieves the point count before ConvexShape constructor in SFML.Net gets a chance to execute and initialise the point count array. 

https://github.com/SFML/SFML.Net/blob/master/src/SFML.Graphics/Shape.cs#L185

https://github.com/SFML/SFML/blob/master/src/SFML/Graphics/Shape.cpp#L133

https://github.com/SFML/SFML/blob/master/src/SFML/Graphics/Shape.cpp#L177

**Comment by DangerRoss** [comment]
As this issue is a base class concerning itself with a sub class thats not fully constructed, I’ve just looked at the other shapes as to why they don’t have this issue. 

Rectangle always has 4 points defined and as for circle… it uses a value type instead of a reference type for the point count which probably means in Circles case, it’s either going to read zero or uninitialized memory during Shape construction. I don’t recall when default field initialisation happens before or after a constructor in C#. Once Circles constructor executes it does set the point count anyway so it doesn’t cause a problem after the object's created.

I think the simplest fix is to have ConvexShape getPointCount have a null check and return zero in that instance. Like Circle, once ConvexShape constructor gets a chance to run it will set the point count accordingly.

**Comment by eXpl0it3r** [comment]
@NedoProgrammer did #206 fix your issue?

**Comment by NedoProgrammer** [comment]
Hello! Sorry for the long delay. #206 did fix the exception issue, but my shape (from the second example) is still different, and I'm not sure why. I'll close the issue anyway, because the exception was the problem 😅. Thank you!
