### ISSUE TITLE
GC ignore SFML objects

### ISSUE THREAD

**Issue by VeryTastyMan** [SFML/SFML.Net#205]
I have function:
![image](https://user-images.githubusercontent.com/64085347/140641158-12d67231-a4ee-45c0-83b0-339183916420.png)

If I understand logic of GC operation correctly, texture will be immediately removed from memory after finish method. But:
![image](https://user-images.githubusercontent.com/64085347/140641198-577cf4db-27e6-4d6a-a32f-f4787611ef1d.png)

What I'm doing wrong? The example is exaggerated, but essence is same.

**Comment by texus** [comment]
Try calling T.Dispose() at the end of the function and see if it reduces memory usage.

I've encountered this before and I think I know why this happens. The GC doesn't run until a certain amount of memory is used. The problem is that it only knows about the managed memory. The Texture class itself is extremely small, but it loads the image in c++ (and thus in unmanaged memory) which the GC doesn't know about.

Eventually the GC will dispose the textures which in turn does free the unmanaged memory, but by that time you probably already created enough textures to fill your entire memory.

I think there is a way to let the GC know about the size of the unmanaged memory, SFML.Net should probably use that internally which should fix the issue if my theory is correct.

**Comment by VeryTastyMan** [comment]
I've already tried calling Dispose() - it's work, but I thought it wasn't quite the right way. It seems there is no other solution. However, thanks for the answer.

**Comment by eXpl0it3r** [comment]
Most SFML.Net classes use internally `ObjectBase` which implements `IDisposable` for the unmanage memory that they allocate from CSFML that is used internally.
As such, all the class instantiation should really utilize `using` (e.g. `using (var texture = new Texture())`), that way dispose is called at the end of using it, regardless whether an exception is thrown.
This is true for any and all objects that implement `IDisposable` unrelated to SFML.

https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=net-5.0
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/using-objects
