### ISSUE TITLE
Music.TimeSpan fields should be public

### ISSUE THREAD

**Issue by Marioalexsan** [SFML/SFML.Net#207]
Is there any reason the Music.TimeSpan fields are private? It's not possible to set any meaningful loop points without having access to them.

```csharp
// Music.cs

/// <summary>
/// Structure defining a Time range. 
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public struct TimeSpan
{
    Time offset;
    Time length;
}
```

**Comment by DangerRoss** [comment]
I don't see any reason for these fields to be private as they're completely unaccessible and not how its documented... its even missing a constructor its supposed to have according to documentation.

I've not used time loops in Audio API before but I'm gonna guess this was an accident when TimeSpan initially added. The fields don't have access modifiers just like C++ code but the languages have different default access for fields... C++ being public and C# private by default.

**Comment by DangerRoss** [comment]
I've been testing this feature with my pull request change and its unearthed a really weird issue I don't know how to progress. 

I would appreciate it if other people gave this a test.

So what i've got so far is when using the LoopPoints property with the TimeSpan which is what making these fields public would allow you to do, it fails to actually set the loop points.

It errors with the message `Music is not in a valid state to assign Loop Points.` https://github.com/SFML/SFML/blob/2.6.x/src/SFML/Audio/Music.cpp#L135 which implies the channel or sample count is getting lost somewhere though I haven't confirmed this.

I went and tested setting loop points in CSFML and it worked fine so that implied a bug in SFML.Net or my pull request. The LoopPoints property returns the correct initialised value but setting it never succeeds.

I can not see what the problem might be. I have also recreated my C test in C# using CSFML P/Invoke functions directly which worked where as using the Music class as you're supposed to doesn't not. Given the Music class is just a wrapper around the same p/invoke functions i'm really not sure what to make of this. Getting it to work directly with the P/Invoke functions implies to me its not a marshalling problem and maybe a obscure memory bug? I'm not sure how the channel or sample count could be lost beyond maybe loosing the CPointer somehow... i'm up for suggestions and would really like to know if others can reproduce this.

```csharp
// Doesn't Work
static void Main(string[] args)
{            
	using var music = new Music("money.mp3");

	music.PlayingOffset = Time.FromSeconds(12);
	music.LoopPoints = new Music.TimeSpan(Time.FromSeconds(12), Time.FromSeconds(24));
	music.Loop = true;

	music.Play();

	Console.Read();

	music.Stop();
}

// Does work
static void Main(string[] args)
{
	IntPtr music = sfMusic_createFromFile("money.mp3");

	if(music == IntPtr.Zero)
	{
		throw new Exception("Music create from file failed");
	}

	sfMusic_setPlayingOffset(music, Time.FromSeconds(12));
	sfMusic_setLoopPoints(music, new Music.TimeSpan(Time.FromSeconds(12), Time.FromSeconds(24)));
	sfMusic_setLoop(music, true);

	sfMusic_play(music);

	Console.Read();

	sfMusic_stop(music);

	sfMusic_destroy(music);
}
```
```C
#include <stdio.h>
#include "SFML/Audio.h"

// Works as expected
int main()
{
	sfMusic* music = sfMusic_createFromFile("money.mp3");
	
	sfMusic_setPlayingOffset(music, sfSeconds(12));

	sfTimeSpan timePoints;
	timePoints.offset = sfSeconds(12);
	timePoints.length = sfSeconds(24);
	sfMusic_setLoopPoints(music, timePoints);

	sfMusic_setLoop(music, sfTrue);

	sfMusic_play(music);

	getchar();

	sfMusic_stop(music);

	sfMusic_destroy(music);
}
```

**Comment by DangerRoss** [comment]
Fix for reported issue above is now in the PR

**Comment by eXpl0it3r** [comment]
Thanks a lot for raising & fixing it 🥳
